logging:
    level:
        blog: WARN
        org: WARN
        springframework: DEBUG
        org.hibernate.SQL: DEBUG
server:
    port: 8080
spring:
    thymeleaf:
        prefix: classpath:/templates/
        suffix: .html
        enabled: true
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        url: jdbc:mysql://localhost:3306/airsoft_test?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: root
        h2:
            console:
                enabled: true
        datasource:
            generate-unique-name: false
            name: users
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true
    mvc:
        format:
            date: yyyy-MM-dd
            time: HH:mm